/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-16 06:38:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ContactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/resources/css/contactUs.css", Long.valueOf(1523860204663L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Friendly  Pets</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t");
      out.write(" /*Contact sectiom*/\r\n");
      out.write(".contact{   \r\n");
      out.write("  /*font-family: 'Teko', sans-serif;*/\r\n");
      out.write("  /*padding-top: 60px;*/\r\n");
      out.write("  width: 100vw;\r\n");
      out.write("  height: 80vh;\r\n");
      out.write("  color : #fff;    \r\n");
      out.write("  display: flex;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-content{\r\n");
      out.write("  text-align: left; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-header{\r\n");
      out.write("  /*font-family: 'Oleo Script', cursive;\r\n");
      out.write("  color:#fcc500;*/\r\n");
      out.write("  padding-left: 20px;\r\n");
      out.write("  font-size: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".contact-section{\r\n");
      out.write("  padding-top: 10px;\r\n");
      out.write("  width: 30vw;\r\n");
      out.write("  height: 80vh;\r\n");
      out.write("  border: solid;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".map-section{\r\n");
      out.write("  padding: 2px 2px 2px 2px;\r\n");
      out.write("  width: 70vw;\r\n");
      out.write("  height: 80vh;\r\n");
      out.write("  border: solid;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("#frameSection{\r\n");
      out.write("  padding-left: 2px;\r\n");
      out.write("  padding-right: 1px;\r\n");
      out.write("  width: 69vw;\r\n");
      out.write("  height: 79vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*Add a line inbetween the textfields and text Area*/\r\n");
      out.write(".form-line{\r\n");
      out.write(" border-style: solid;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group{\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("  font-size: 1.3em;\r\n");
      out.write("  line-height: 1em;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("  font-size: 1.3em;\r\n");
      out.write("  color: #080808;\r\n");
      out.write("}\r\n");
      out.write("textarea.form-control {\r\n");
      out.write("    height: 120px;\r\n");
      out.write("   /* margin-top: px;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit{\r\n");
      out.write("  font-size: 1.1em;\r\n");
      out.write("  float: ;\r\n");
      out.write("  width: 150px;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"headerSection\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"contact contentSection\">\r\n");
      out.write("\t\t<div class=\"contact-section w3-red\">\r\n");
      out.write("\t\t\t<div class=\"container \">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8  \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"title\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-size: 25px; font-color: black;\">Get in touch\r\n");
      out.write("\t\t\t\t\t\t\t\t\twith us</span></label><br> <label for=\"exampleInputUsername\">Your\r\n");
      out.write("\t\t\t\t\t\t\t\tname</label> <input type=\"text\" class=\"form-control\" id=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\" Enter Name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail\">Email Address</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"email\" class=\"form-control\" id=\"exampleInputEmail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\" Enter Email id\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"telephone\">Mobile No.</label> <input type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"telephone\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\" Enter 10-digit mobile no.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"description\"> Message</label>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter Your Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"padding-top: 7px\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-paper-plane\" aria-hidden=\"true\"></i> Send\r\n");
      out.write("\t\t\t\t\t\t\t\tMessage\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--Close of contact  -->\r\n");
      out.write("\t\t<div class=\"map-section\">\r\n");
      out.write("\t\t\t<iframe id=\"frameSection\"\r\n");
      out.write("\t\t\t\tsrc=\"https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d3736489.7218514383!2d90.21589792292741!3d23.857125486636733!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1506502314230\"\r\n");
      out.write("\t\t\t\t|\t  frameborder=\"0\" style=\"border: 0\" allowfullscreen></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footerSection\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
