/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-13 06:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newReg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html class=\"supernova\"><head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"alternate\" type=\"application/json+oembed\" href=\"https://www.jotform.com/oembed/?format=json&amp;url=http%3A%2F%2Fwww.jotform.com%2Fform%2F80906816621458\" title=\"oEmbed Form\"><link rel=\"alternate\" type=\"text/xml+oembed\" href=\"https://www.jotform.com/oembed/?format=xml&amp;url=http%3A%2F%2Fwww.jotform.com%2Fform%2F80906816621458\" title=\"oEmbed Form\">\r\n");
      out.write("<meta property=\"og:title\" content=\"JotForm\" >\r\n");
      out.write("<meta property=\"og:url\" content=\"http://www.jotform.me/form/80906816621458\" >\r\n");
      out.write("<meta property=\"og:description\" content=\"Please click the link to complete this form.\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://cdn.jotfor.ms/favicon.ico\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" />\r\n");
      out.write("<meta name=\"HandheldFriendly\" content=\"true\" />\r\n");
      out.write("<title>JotForm</title>\r\n");
      out.write("<link href=\"https://cdn.jotfor.ms/static/formCss.css?3.3.5398\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link type=\"text/css\" media=\"print\" rel=\"stylesheet\" href=\"https://cdn.jotfor.ms/css/printForm.css?3.3.5398\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"https://cdn.jotfor.ms/css/styles/nova.css?3.3.5398\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"https://cdn.jotfor.ms/themes/CSS/54a7a9e325d790551f8b4567.css?\"/>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://shots.jotform.com/elton/genericTheme.css');\r\n");
      out.write("\r\n");
      out.write("    .form-label-left{\r\n");
      out.write("        width:150px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-line{\r\n");
      out.write("        padding-top:12px;\r\n");
      out.write("        padding-bottom:12px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-label-right{\r\n");
      out.write("        width:150px;\r\n");
      out.write("    }\r\n");
      out.write("    body, html{\r\n");
      out.write("        margin:0;\r\n");
      out.write("        padding:0;\r\n");
      out.write("        background:rgba(0, 0, 0, 0.72);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-all{\r\n");
      out.write("        margin:0px auto;\r\n");
      out.write("        padding-top:0px;\r\n");
      out.write("        width:550px;\r\n");
      out.write("        color:rgb(255, 255, 255) !important;\r\n");
      out.write("        font-family:'Muli';\r\n");
      out.write("        font-size:16px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-radio-item label, .form-checkbox-item label, .form-grading-label, .form-header{\r\n");
      out.write("        color: false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jotfor.ms/static/prototype.forms.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"https://cdn.jotfor.ms/static/jotform.forms.js?3.3.5398\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   JotForm.init(function(){\r\n");
      out.write("      setTimeout(function() {\r\n");
      out.write("          $('input_26').hint('ex: myname@example.com');\r\n");
      out.write("       }, 20);\r\n");
      out.write("    /*INIT-END*/\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("   JotForm.prepareCalculationsOnTheFly([null,null,null,null,null,null,null,{\"name\":\"register\",\"qid\":\"7\",\"text\":\"Register\",\"type\":\"control_button\"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{\"name\":\"registerTo\",\"qid\":\"24\",\"text\":\"Register to Friendly Pets\",\"type\":\"control_head\"},{\"name\":\"name\",\"qid\":\"25\",\"text\":\"Name\",\"type\":\"control_fullname\"},{\"name\":\"email26\",\"qid\":\"26\",\"text\":\"E-mail\",\"type\":\"control_email\"},{\"description\":\"\",\"name\":\"phoneNumber\",\"qid\":\"27\",\"text\":\"Phone Number\",\"type\":\"control_phone\"},{\"description\":\"\",\"name\":\"userName\",\"qid\":\"28\",\"subLabel\":\"\",\"text\":\"User Name\",\"type\":\"control_textbox\"}]);\r\n");
      out.write("   setTimeout(function() {\r\n");
      out.write("JotForm.paymentExtrasOnTheFly([null,null,null,null,null,null,null,{\"name\":\"register\",\"qid\":\"7\",\"text\":\"Register\",\"type\":\"control_button\"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{\"name\":\"registerTo\",\"qid\":\"24\",\"text\":\"Register to Friendly Pets\",\"type\":\"control_head\"},{\"name\":\"name\",\"qid\":\"25\",\"text\":\"Name\",\"type\":\"control_fullname\"},{\"name\":\"email26\",\"qid\":\"26\",\"text\":\"E-mail\",\"type\":\"control_email\"},{\"description\":\"\",\"name\":\"phoneNumber\",\"qid\":\"27\",\"text\":\"Phone Number\",\"type\":\"control_phone\"},{\"description\":\"\",\"name\":\"userName\",\"qid\":\"28\",\"subLabel\":\"\",\"text\":\"User Name\",\"type\":\"control_textbox\"}]);}, 20); \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form class=\"jotform-form\" action=\"\" method=\"post\" name=\"form_80906816621458\" id=\"80906816621458\" accept-charset=\"utf-8\">\r\n");
      out.write("  <input type=\"hidden\" name=\"formID\" value=\"80906816621458\" />\r\n");
      out.write("  <div class=\"form-all\">\r\n");
      out.write("    <ul class=\"form-section page-section\">\r\n");
      out.write("      <li id=\"cid_24\" class=\"form-input-wide\" data-type=\"control_head\">\r\n");
      out.write("        <div class=\"form-header-group \">\r\n");
      out.write("          <div class=\"header-text httal htvam\">\r\n");
      out.write("            <h2 id=\"header_24\" class=\"form-header\" data-component=\"header\">\r\n");
      out.write("              Register to Friendly Pets\r\n");
      out.write("            </h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"form-line jf-required\" data-type=\"control_fullname\" id=\"id_25\">\r\n");
      out.write("        <label class=\"form-label form-label-left form-label-auto\" id=\"label_25\" for=\"first_25\">\r\n");
      out.write("          Name\r\n");
      out.write("          <span class=\"form-required\">\r\n");
      out.write("            *\r\n");
      out.write("          </span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <div id=\"cid_25\" class=\"form-input jf-required\">\r\n");
      out.write("          <div data-wrapper-react=\"true\">\r\n");
      out.write("            <span class=\"form-sub-label-container\" style=\"vertical-align:top;\">\r\n");
      out.write("              <input type=\"text\" id=\"first_25\" name=\"q25_name[first]\" class=\"form-textbox validate[required]\" size=\"10\" value=\"\" data-component=\"first\" required=\"\" />\r\n");
      out.write("              <label class=\"form-sub-label\" for=\"first_25\" id=\"sublabel_first\" style=\"min-height:13px;\"> First Name </label>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"form-sub-label-container\" style=\"vertical-align:top;\">\r\n");
      out.write("              <input type=\"text\" id=\"last_25\" name=\"q25_name[last]\" class=\"form-textbox validate[required]\" size=\"15\" value=\"\" data-component=\"last\" required=\"\" />\r\n");
      out.write("              <label class=\"form-sub-label\" for=\"last_25\" id=\"sublabel_last\" style=\"min-height:13px;\"> Last Name </label>\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"form-line jf-required\" data-type=\"control_textbox\" id=\"id_28\">\r\n");
      out.write("        <label class=\"form-label form-label-left form-label-auto\" id=\"label_28\" for=\"input_28\">\r\n");
      out.write("          User Name\r\n");
      out.write("          <span class=\"form-required\">\r\n");
      out.write("            *\r\n");
      out.write("          </span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <div id=\"cid_28\" class=\"form-input jf-required\">\r\n");
      out.write("          <input type=\"text\" id=\"input_28\" name=\"q28_userName\" data-type=\"input-textbox\" class=\"form-textbox validate[required]\" size=\"20\" value=\"\" data-component=\"textbox\" required=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"form-line jf-required\" data-type=\"control_email\" id=\"id_26\">\r\n");
      out.write("        <label class=\"form-label form-label-left form-label-auto\" id=\"label_26\" for=\"input_26\">\r\n");
      out.write("          E-mail\r\n");
      out.write("          <span class=\"form-required\">\r\n");
      out.write("            *\r\n");
      out.write("          </span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <div id=\"cid_26\" class=\"form-input jf-required\">\r\n");
      out.write("          <input type=\"email\" id=\"input_26\" name=\"q26_email26\" class=\"form-textbox validate[required, Email]\" size=\"32\" value=\"\" placeholder=\"ex: myname@example.com\" data-component=\"email\" required=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"form-line jf-required\" data-type=\"control_phone\" id=\"id_27\">\r\n");
      out.write("        <label class=\"form-label form-label-left form-label-auto\" id=\"label_27\" for=\"input_27_area\">\r\n");
      out.write("          Phone Number\r\n");
      out.write("          <span class=\"form-required\">\r\n");
      out.write("            *\r\n");
      out.write("          </span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <div id=\"cid_27\" class=\"form-input jf-required\">\r\n");
      out.write("          <div data-wrapper-react=\"true\">\r\n");
      out.write("            <span class=\"form-sub-label-container\" style=\"vertical-align:top;\">\r\n");
      out.write("              <input type=\"tel\" id=\"input_27_area\" name=\"q27_phoneNumber[area]\" class=\"form-textbox validate[required]\" size=\"3\" value=\"\" data-component=\"areaCode\" required=\"\" />\r\n");
      out.write("              <span class=\"phone-separate\">\r\n");
      out.write("                 -\r\n");
      out.write("              </span>\r\n");
      out.write("              <label class=\"form-sub-label\" for=\"input_27_area\" id=\"sublabel_area\" style=\"min-height:13px;\"> Area Code </label>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"form-sub-label-container\" style=\"vertical-align:top;\">\r\n");
      out.write("              <input type=\"tel\" id=\"input_27_phone\" name=\"q27_phoneNumber[phone]\" class=\"form-textbox validate[required]\" size=\"8\" value=\"\" data-component=\"phone\" required=\"\" />\r\n");
      out.write("              <label class=\"form-sub-label\" for=\"input_27_phone\" id=\"sublabel_phone\" style=\"min-height:13px;\"> Phone Number </label>\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"form-line\" data-type=\"control_button\" id=\"id_7\">\r\n");
      out.write("        <div id=\"cid_7\" class=\"form-input-wide\">\r\n");
      out.write("          <div style=\"margin-left:156px;\" class=\"form-buttons-wrapper\">\r\n");
      out.write("            <button id=\"input_7\" type=\"submit\" class=\"form-submit-button\" data-component=\"button\">\r\n");
      out.write("              Register\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li style=\"display:none\">\r\n");
      out.write("        Should be Empty:\r\n");
      out.write("        <input type=\"text\" name=\"website\" value=\"\" />\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("  JotForm.showJotFormPowered = \"new_footer\";\r\n");
      out.write("  </script>\r\n");
      out.write("  <input type=\"hidden\" id=\"simple_spc\" name=\"simple_spc\" value=\"80906816621458\" />\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  document.getElementById(\"si\" + \"mple\" + \"_spc\").value = \"80906816621458-80906816621458\";\r\n");
      out.write("  </script>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\">JotForm.ownerView=true;</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
